name: ASP. NET Core Continuous Integration

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1

    - name: Set Up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.302

    - name: Run Tests
    run: dotnet test